//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ.MerianPartyStore.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int IdBanner { get; set; }
        public string Imagen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
    }
}
