//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ.MerianPartyStore.DL.DM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBMerianPartyStoreEntities : DbContext
    {
        public DBMerianPartyStoreEntities()
            : base("name=DBMerianPartyStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Configuracion> Configuracion { get; set; }
        public virtual DbSet<Foto> Foto { get; set; }
        public virtual DbSet<FotoInvitacion> FotoInvitacion { get; set; }
        public virtual DbSet<Invitacion> Invitacion { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ServiciosAdicionales> ServiciosAdicionales { get; set; }
        public virtual DbSet<TipoVariante> TipoVariante { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Variante> Variante { get; set; }
        public virtual DbSet<VarianteProducto> VarianteProducto { get; set; }
    
        [DbFunction("DBMerianPartyStoreEntities", "CategoriasDescendientes")]
        public virtual IQueryable<CategoriasDescendientes_Result> CategoriasDescendientes(Nullable<int> idCategoria)
        {
            var idCategoriaParameter = idCategoria.HasValue ?
                new ObjectParameter("IdCategoria", idCategoria) :
                new ObjectParameter("IdCategoria", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CategoriasDescendientes_Result>("[DBMerianPartyStoreEntities].[CategoriasDescendientes](@IdCategoria)", idCategoriaParameter);
        }
    }
}
