//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ.MerianPartyStore.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invitacion()
        {
            this.FotoInvitacion = new HashSet<FotoInvitacion>();
        }
    
        public int IdInvitacion { get; set; }
        public string Cliente { get; set; }
        public Nullable<System.DateTime> FechaInvitacion { get; set; }
        public Nullable<System.TimeSpan> HoraInvitacion { get; set; }
        public string Color { get; set; }
        public string TelefonoContactoInvitacion { get; set; }
        public string TelefonoContactoInvitacion2 { get; set; }
        public string Descripcion { get; set; }
        public string UbicacionGoogleMaps { get; set; }
        public string UbicacionGoogleMaps2 { get; set; }
        public string TipoInvitacion { get; set; }
        public string UrlPDFInvitacion { get; set; }
        public string Audio { get; set; }
        public string Fondo { get; set; }
        public string LinkMesaRegalos { get; set; }
        public string LinkCalendario { get; set; }
        public string TipoEntidadBancaria { get; set; }
        public string NumeroCuenta { get; set; }
        public string CCI { get; set; }
        public string CountdownColor { get; set; }
        public string Titulo { get; set; }
        public string VideoInvitacion { get; set; }
        public string ImagenItinerario { get; set; }
        public Nullable<bool> MostrarIcono { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Eliminado { get; set; }
        public Nullable<int> TiempoCarga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FotoInvitacion> FotoInvitacion { get; set; }
    }
}
