//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ.MerianPartyStore.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class VarianteProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VarianteProducto()
        {
            this.Foto = new HashSet<Foto>();
            this.ServiciosAdicionales = new HashSet<ServiciosAdicionales>();
            this.Variante = new HashSet<Variante>();
        }
    
        public int IdVarianteProducto { get; set; }
        public int IdProducto { get; set; }
        public string Link { get; set; }
        public Nullable<double> Precio { get; set; }
        public Nullable<double> PrecioPromocional { get; set; }
        public bool Activo { get; set; }
    
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiciosAdicionales> ServiciosAdicionales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Variante> Variante { get; set; }
    }
}
