//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CJ.MerianPartyStore.DL.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variante()
        {
            this.VarianteProducto = new HashSet<VarianteProducto>();
        }
    
        public int IdVariante { get; set; }
        public int IdTipoVariante { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
    
        public virtual TipoVariante TipoVariante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VarianteProducto> VarianteProducto { get; set; }
    }
}
